// src/router-config.js
// React Router에서도 사용하는 라우팅 상수/매핑

export const LAST_PAGE_KEY = 'invex_last_page_v1';

// PAGE_LOADERS: 기존 router.js에서 그대로 복사 (renderXxxPage 함수 로더)
export const PAGE_LOADERS = {
  home:            () => import('./page-home.js').then(m => m.renderHomePage),
  upload:          () => import('./page-upload.js').then(m => m.renderUploadPage),
  mapping:         () => import('./page-mapping.js').then(m => m.renderMappingPage),
  inventory:       () => import('./page-inventory.js').then(m => m.renderInventoryPage),
  in:              () => import('./page-inout.js').then(m => m.renderInPage),
  out:             () => import('./page-inout.js').then(m => m.renderOutPage),
  summary:         () => import('./page-summary.js').then(m => m.renderSummaryPage),
  scanner:         () => import('./page-scanner.js').then(m => m.renderScannerPage),
  documents:       () => import('./page-documents.js').then(m => m.renderDocumentsPage),
  dashboard:       () => import('./page-dashboard.js').then(m => m.renderDashboardPage),
  transfer:        () => import('./page-transfer.js').then(m => m.renderTransferPage),
  ledger:          () => import('./page-ledger.js').then(m => m.renderLedgerPage),
  settings:        () => import('./page-settings.js').then(m => m.renderSettingsPage),
  vendors:         () => import('./page-vendors.js').then(m => m.renderVendorsPage),
  stocktake:       () => import('./page-stocktake.js').then(m => m.renderStocktakePage),
  bulk:            () => import('./page-bulk.js').then(m => m.renderBulkPage),
  costing:         () => import('./page-costing.js').then(m => m.renderCostingPage),
  labels:          () => import('./page-labels.js').then(m => m.renderLabelsPage),
  accounts:        () => import('./page-accounts.js').then(m => m.renderAccountsPage),
  warehouses:      () => import('./page-warehouses.js').then(m => m.renderWarehousesPage),
  roles:           () => import('./page-roles.js').then(m => m.renderRolesPage),
  api:             () => import('./page-api.js').then(m => m.renderApiPage),
  billing:         () => import('./page-billing.js').then(m => m.renderBillingPage),
  admin:           () => import('./page-admin.js').then(m => m.renderAdminPage),
  mypage:          () => import('./page-mypage.js').then(m => m.renderMyPage),
  guide:           () => import('./page-guide.js').then(m => m.renderGuidePage),
  support:         () => import('./page-support.js').then(m => m.renderSupportPage),
  team:            () => import('./page-team.js').then(m => m.renderTeamPage),
  'tax-reports':   () => import('./page-tax-reports.js').then(m => m.renderTaxReportsPage),
  profit:          () => import('./page-profit.js').then(m => m.renderProfitPage),
  backup:          () => import('./page-backup.js').then(m => m.renderBackupPage),
  orders:          () => import('./page-orders.js').then(m => m.renderOrdersPage),
  forecast:        () => import('./page-forecast.js').then(m => m.renderForecastPage),
  referral:        () => import('./page-referral.js').then(m => m.renderReferralPage),
  'weekly-report': () => import('./page-weekly-report.js').then(m => m.renderWeeklyReportPage),
  pos:             () => import('./page-pos.js').then(m => m.renderPosPage),
  'hr-dashboard':  () => import('./page-hr-dashboard.js').then(m => m.renderHrDashboardPage),
  employees:       () => import('./page-employees.js').then(m => m.renderEmployeesPage),
  attendance:      () => import('./page-attendance.js').then(m => m.renderAttendancePage),
  payroll:         () => import('./page-payroll.js').then(m => m.renderPayrollPage),
  leaves:          () => import('./page-leaves.js').then(m => m.renderLeavesPage),
  severance:       () => import('./page-severance.js').then(m => m.renderSeverancePage),
  'yearend-settlement': () => import('./page-yearend-settlement.js').then(m => m.renderYearendSettlementPage),
  auditlog:        () => import('./audit-log.js').then(m => m.renderAuditLogPage),
  'hub-inventory': () => import('./page-hubs.js').then(m => m.renderHubInventory),
  'hub-warehouse': () => import('./page-hubs.js').then(m => m.renderHubWarehouse),
  'hub-order':     () => import('./page-hubs.js').then(m => m.renderHubOrder),
  'hub-report':    () => import('./page-hubs.js').then(m => m.renderHubReport),
  'hub-documents': () => import('./page-hubs.js').then(m => m.renderHubDocuments),
  'hub-settings':  () => import('./page-hubs.js').then(m => m.renderHubSettings),
  'hub-support':   () => import('./page-hubs.js').then(m => m.renderHubSupport),
  'hub-hr':        () => import('./page-hubs.js').then(m => m.renderHubHr),
};

// 페이지 라벨 (브레드크럼용)
export const PAGE_LABELS = {
  home: '대시보드',
  inventory: '재고현황',
  in: '입고관리',
  out: '출고관리',
  ledger: '수불관리',
  upload: '파일 업로드',
  mapping: '컬럼 매핑',
  summary: '요약 보고',
  profit: '손익 분석',
  costing: '원가 분석',
  dashboard: '고급 분석',
  accounts: '매출·매입',
  scanner: '바코드 스캐너',
  documents: '문서 생성',
  orders: '발주 관리',
  forecast: '수요 예측',
  vendors: '거래처 관리',
  warehouses: '다중 창고 관리',
  transfer: '창고 이동',
  stocktake: '재고 실사',
  bulk: '일괄 처리',
  labels: '라벨 출력',
  settings: '기본 설정',
  team: '팀 관리',
  roles: '권한 관리',
  api: 'API 연동',
  billing: '구독 관리',
  backup: '백업·복원',
  mypage: '마이페이지',
  guide: '사용 가이드',
  support: '고객 문의',
  referral: '추천 프로그램',
  'weekly-report': '주간 보고서',
  'tax-reports': '세무·회계 서류',
  pos: 'POS 매출분석',
  admin: '관리자',
  auditlog: '감사 추적',
  'hr-dashboard': 'HR 대시보드',
  employees: '직원 관리',
  attendance: '근태 관리',
  payroll: '급여 계산',
  leaves: '휴가·연차',
  severance: '퇴직금 계산',
  'yearend-settlement': '연말정산',
};
